name: Did Verified Car Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |

            echo "🚀 Pulling latest code..."
            cd /var/www/did-verifiedcar || exit

            git fetch origin
            git reset --hard origin/main

            echo "📦 Installing dependencies..."
            npm install --production

            echo "♻ Restarting application..."
            pm2 reload did-resolver

            echo "✅ Deployment Complete!"
